In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('winequality-red.csv')

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
#sns.pairplot(df,hue='quality',palette='Set1')

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop('quality', axis = 1)
y = df['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [7]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
predictions = dtree.predict(X_test)

In [8]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))


             precision    recall  f1-score   support

          3       0.50      0.40      0.44         5
          4       0.29      0.17      0.22        23
          5       0.65      0.71      0.68       197
          6       0.65      0.58      0.62       200
          7       0.46      0.57      0.51        49
          8       0.12      0.17      0.14         6

avg / total       0.61      0.61      0.60       480



In [9]:
print(confusion_matrix(y_test,predictions))

[[  2   1   1   1   0   0]
 [  2   4  11   4   2   0]
 [  0   7 139  43   6   2]
 [  0   1  56 117  23   3]
 [  0   1   6  12  28   2]
 [  0   0   0   3   2   1]]


In [10]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [11]:
rfc_pred = rfc.predict(X_test)

In [12]:
print(confusion_matrix(y_test,rfc_pred))

[[  0   0   5   0   0   0]
 [  1   0  15   7   0   0]
 [  0   1 154  41   1   0]
 [  0   0  48 132  20   0]
 [  0   0   5  16  28   0]
 [  0   0   0   3   3   0]]


In [13]:
print(classification_report(y_test,rfc_pred))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         5
          4       0.00      0.00      0.00        23
          5       0.68      0.78      0.73       197
          6       0.66      0.66      0.66       200
          7       0.54      0.57      0.55        49
          8       0.00      0.00      0.00         6

avg / total       0.61      0.65      0.63       480



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
